// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    }
    if (defaultTargetPlatform == TargetPlatform.macOS) {
      return macos;
    }
    if (defaultTargetPlatform == TargetPlatform.windows) {
      return windows;
    }
    if (defaultTargetPlatform == TargetPlatform.linux) {
      return linux;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRHqFI9LydOvJCobxrmRcnvhmcG8DgY9w',
    appId: '1:398232009989:android:1512601bfdadb70b220b6c',
    messagingSenderId: '398232009989',
    projectId: 'zk-event-entry',
    storageBucket: 'zk-event-entry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRHqFI9LydOvJCobxrmRcnvhmcG8DgY9w',
    appId: '1:398232009989:ios:1512601bfdadb70b220b6c',
    messagingSenderId: '398232009989',
    projectId: 'zk-event-entry',
    storageBucket: 'zk-event-entry.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRHqFI9LydOvJCobxrmRcnvhmcG8DgY9w',
    appId: '1:398232009989:macos:1512601bfdadb70b220b6c',
    messagingSenderId: '398232009989',
    projectId: 'zk-event-entry',
    storageBucket: 'zk-event-entry.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRHqFI9LydOvJCobxrmRcnvhmcG8DgY9w',
    appId: '1:398232009989:windows:1512601bfdadb70b220b6c',
    messagingSenderId: '398232009989',
    projectId: 'zk-event-entry',
    storageBucket: 'zk-event-entry.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBRHqFI9LydOvJCobxrmRcnvhmcG8DgY9w',
    appId: '1:398232009989:linux:1512601bfdadb70b220b6c',
    messagingSenderId: '398232009989',
    projectId: 'zk-event-entry',
    storageBucket: 'zk-event-entry.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRHqFI9LydOvJCobxrmRcnvhmcG8DgY9w',
    appId: '1:398232009989:web:1512601bfdadb70b220b6c',
    messagingSenderId: '398232009989',
    projectId: 'zk-event-entry',
    storageBucket: 'zk-event-entry.firebasestorage.app',
    measurementId: 'G-7TZBLZ9K3M',
  );
}
